---
- name: "Install Kubernetes"
  hosts: cluster
  gather_facts: true
  become: true
  tags: prereq
  roles:
    - common
    # TODO: move kubernetes common to all cluster nodes
    # - kubernetes/common


- name: "Setup Control Plane Nodes"
  hosts: master
  gather_facts: true
  become: true
  tags: install_kubernetes
  roles:
    # TODO: remove
    - kubernetes/common
    - kubernetes/master

- name: "Setup Worker Nodes"
  hosts: worker
  gather_facts: true
  become: true
  tags: install_kubernetes
  roles:
    # TODO: remove
    - kubernetes/common
    - kubernetes/worker

- name: "Install extras"
  hosts: cluster
  roles:
    - role: extras/local-path-provisioner
      tags: install_local_path

- name: "Install extras"
  hosts: master
  tags: install_extras
  become: false
  roles:
    - role: extras/helm
      tags: install_helm
    - role: extras/metallb
      tags: install_metallb
    - role: extras/ingress-nginx
      tags: install_ingress

