---
cluster_name: "mycluster"

kubernetes_version: "1.30"
calico_version: "3.28.0"

cni_plugin: "calico"

kubernetes_apt_release_channel: "stable"
kubernetes_apt_keyring_file: "/etc/apt/keyrings/kubernetes-apt-keyring.asc"
kubernetes_apt_repository: "deb [signed-by={{ kubernetes_apt_keyring_file }}] https://pkgs.k8s.io/core:/{{ kubernetes_apt_release_channel }}:/v{{ kubernetes_version }}/deb/ /"

kubernetes_kubeadm_kubelet_config_file_path: "/etc/kubernetes/kubeadm-kubelet-config.yml"
kubernetes_kubeadm_init_extra_opts: ""
kubernetes_apiserver_advertise_address: ""

kubernetes_init_configuration:
  localAPIEndpoint:
    advertiseAddress: "{{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}"
    bindPort: 6443

kubernetes_cluster_configuration:
  clusterName: "{{ cluster_name }}"
  networking:
    podSubnet: "10.244.0.0/24"

kubernetes_kubelet_configuration:
  cgroupDriver: "systemd"

kubernetes_kubeproxy_configuration: {}

calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/calico.yaml"
