---
# OS preparation
- name: Ensure br_netfilter is enabled.
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10

- name: Let iptables see bridged traffic.
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10

- name: Disabling UFW
  community.general.ufw:
    state: disabled

- name: "Remove swapfile from /etc/fstab"
  ansible.builtin.mount:
    name: swap
    fstype: swap
    state: absent

- name: "Disable swap"
  ansible.builtin.shell: swapoff -a
  when: ansible_swaptotal_mb > 0
