---
# Install packages
- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
