---
cluster_name: "mycluster"

kubernetes_kubeadm_kubelet_config_file_path: "/etc/kubernetes/kubeadm-kubelet-config.yml"
kubernetes_kubeadm_init_extra_opts: ""
kubernetes_apiserver_advertise_address: ""

kubernetes_init_configuration:
  localAPIEndpoint:
    advertiseAddress: "{{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}"
    bindPort: 6443

kubernetes_cluster_configuration:
  clusterName: "{{ cluster_name }}"
  networking:
    podSubnet: "10.244.0.0/24"

kubernetes_kubelet_configuration:
  cgroupDriver: "systemd"

kubernetes_kubeproxy_configuration: {}
