---
- name: Modify kube-proxy settings for MetalLB
  block:
    - name: Get kube-proxy config map
      ansible.builtin.command: |
        kubectl get configmap kube-proxy -n kube-system -o yaml
      register: kube_proxy_cmd
      failed_when: false

    - name: Verify if kube-proxy config needs updating
      ansible.builtin.command: >-
        kubectl get configmap kube-proxy -n kube-system -o yaml |
        sed -e "s/strictARP: false/strictARP: true/" |
        kubectl diff -f - -n kube-system
      register: kube_proxy_diff_cmd
      when: kube_proxy_cmd.rc == 0
      failed_when: false

    - name: Set update_kube_proxy secret to true
      ansible.builtin.set_fact:
        update_kube_proxy: true
      when:
        kube_proxy_cmd.rc == 0 and kube_proxy_diff_cmd.rc > 0

    - name: Update kube-proxy config map
      ansible.builtin.shell: >-
        kubectl get configmap kube-proxy -n kube-system -o yaml |
        sed -e "s/strictARP: false/strictARP: true/" |
        kubectl apply -f - -n kube-system
      changed_when: true
      when:
        update_kube_proxy | default(false)

- name: Add MetalLB Helm repo
  kubernetes.core.helm_repository:
    repo_name: metallb
    repo_url: https://metallb.github.io/metallb
    state: present

- name: Install MetalLB using Helm
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: "{{ metallb_namespace }}"
    create_namespace: true

- name: Wait for MetalLB controller to be running
  ansible.builtin.command: >-
    kubectl rollout status -n {{ metallb_namespace }} deployment \
      -l app.kubernetes.io/name=metallb,app.kubernetes.io/component=controller \
      --timeout=2m
  when:
    - inventory_hostname == groups['master'][0]

- name: MetalLB | Create layer2 configuration
  kubernetes.core.k8s:
    template: "l2.yml.j2"
    state: "present"
